[build]
  base = "resume-chatbot"
  command = "npm install --legacy-peer-deps && npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/Resume_Das_2024.pdf"]