[build]
  base = "resume-chatbot"  # Path to the chatbot folder
  publish = "resume-chatbot/public"  
  command = "npm install --legacy-peer-deps && npm run build"

[functions]
  directory = "resume-chatbot/functions"  



  
